cleaned up testing and installation.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,13 +1,16 @@
+PREFIX  ?= /usr/local
 LIBDIR   = ../build
 CPPFLAGS = -I../include
 CFLAGS   = -g -Wall -pedantic-errors -std=c11 $(SANFLAGS)
 LDFLAGS  = -L$(LIBDIR) -l211 $(SANFLAGS)
 SANFLAGS = -fsanitize=address,undefined
+LIBENV   = LD_LIBRARY_PATH=$(LIBDIR)
 
 TESTS    = use_lib211_test check_string_test
 EXES     = $(TESTS:%=build/%)
+SYS_EXES = $(TESTS:%=build/%.system)
 
-LIBENV   = LD_LIBRARY_PATH=$(LIBDIR)
+test-install build/%.system: LIBDIR = $(PREFIX)/lib
 
 test: $(EXES)
 	for test in $(TESTS); do \
@@ -16,17 +19,21 @@ test: $(EXES)
 	    echo; \
 	done
 
-test-install: $(EXES)
+test-install: $(SYS_EXES)
 	for test in $(TESTS); do \
 	    printf '\n*** Running %s: ***\n' $$test; \
-	    build/$$test 2>&1; \
+	    $(LIBENV) build/$$test 2>&1 || echo "Error exit: $$?" >&2; \
+	    echo; \
 	done
 
 build/%: build/%.o
-	cc -o $@ $^ $(SANFLAGS) $(LDFLAGS)
+	cc -o $@ $^ $(LDFLAGS)
+
+build/%.system: build/%.o
+	cc -o $@ $^ $(LDFLAGS)
 
 build/%.o: %.c | build
-	cc -c -o $@ $^ $(SANFLAGS) $(CPPFLAGS) $(CFLAGS)
+	cc -c -o $@ $^ $(CPPFLAGS) $(CFLAGS)
 
 build:
 	mkdir -p build
